name: flutter_booking_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - images/booking.png
    - images/cs.png
    - images/foto_profil.jpg
    - images/futsal.jpg
    - images/futsal.png
    - images/lapangan.png
    - images/logo.png
    - images/lapangan/A.jpg
    - images/lapangan/B.jpg
